version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    restart: unless-stopped
